config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :reviews
  resources :blogs
  resources :properties do 
    resources :rmrms, only: [:create]
  end 
  resources :types
 devise_for :users, controllers: {sessions: 'users/sessions' } 
 

 
 
 get 'contact', to: 'messages#new', as: 'contact'
 post 'contact', to: 'messages#create'

 root 'properties#index'

 get 'about' => 'properties#about', as: 'about'

end

app/models/property.rb
class Property < ActiveRecord::Base
    
    belongs_to :type
    belongs_to :user
    has_many :reviews
    has_many :rmrms
    accepts_nested_attributes_for :reviews
    
   geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  

    
    validates :title, :description,:price,:address, presence: true
    validates :description, length: { minimum: 20 }
    validates :price, numericality: true

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
  
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:title, :description, :price, :beds, :baths, :address, :city, :zip_code, :latitude, :longitude, :type_id, :user_id)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<% if user_signed_in?%>



<nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                      <%= link_to 'Home', properties_path%>
                    </li>
                    <li>
                      <%= link_to 'About Us', about_path%>
                    </li>
                     <li>
                     <%= link_to 'contact Us', contact_path%>
                     </li>
                
                
                    <% if user_signed_in? %>
                    Wellcome <strong><%= current_user.first_name %>&nbsp;&nbsp;</strong>
 
                   <%= link_to 'Edit profile', edit_user_registration_path %>|
                   <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
                 
                 <% else %>
                   <%= link_to "Sign up", new_user_registration_path  %> |
                   <%= link_to "Login", new_user_session_path %>
                 <% end %>

  
   </ul>
            </div>






<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  
   <h2>Post New property</h2> 
  <div class="brand-before"> 
   <%= f.label :Type %> <br>
  <%= f.select :type_id,Type.all.order('property_type').map { |t| [t.property_type,t.id] } ,prompt:"[--your property type--]", class: "form-control"  %>
  </div>
  <br>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= number_to_currency(f.text_field :price) %>
    
  </div>
  <div class="field">
    <%= f.label :beds %><br>
    <%= f.number_field :beds, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :baths %><br>
    <%= f.number_field :baths, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code, class: "form-control" %>
  </div>
  
  

  
  <div> 
 <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  
  <br>
  
  <br>
  
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>






<% end %>


<% else %>
<%= 'sorry you must to login first' %>

<% end %>

app/views/properties/_rmrm.html.erb
<h3>Assets for the project</h3>



<ul>
  <%= @property.rmrms.each do |rmrm| %>
    <li>
        <%= rmrm.file %>
    </li>
  <% end %>


<% form_for [ @property, @property.rmrms.build ], multipart: true do |f| %>
<p>
  <% f.file_field :file %>
   <%f.hidden_field :property_id, :value => params[:id] %>
  <% f.submit %>
</p>
 
<% end %>

app/views/properties/about.html.erb
<nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                      <%= link_to 'Home', properties_path%>
                    </li>
                    <li>
                      <%= link_to 'About Us', about_path%>
                    </li>
                     <li>
                     <%= link_to 'contact Us', contact_path%>
                     </li>
                
                
                    <% if user_signed_in? %>
                    Wellcome <strong><%= current_user.first_name %>&nbsp;&nbsp;</strong>
 
                   <%= link_to 'Edit profile', edit_user_registration_path %>|
                   <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
                 
                 <% else %>
                   <%= link_to "Sign up", new_user_registration_path  %> |
                   <%= link_to "Login", new_user_session_path %>
                 <% end %>

  
   </ul>
            </div>





 <div class="row">
            <div class="box">
                <div class="col-lg-10">
                   
       <h1>Locality Real Estate</h1>
	<hr>
	<p>This real estate project was built by Devbootstrap cohort 2017</p><br>
	<p>I can create Rails application Real Estate. In this application have some feature like: </p><br>

		<li>Can publish your property with your details</li>
		<li>Can show property that peoples create</li>
		<li>Can login to edit or delet your property</li>

	
	
	<h3 class="aside">Contact person</h3>
			<hr/>
			<p>In case you want to get in touch with us please feel free to call or email us.</p>
			<div id="contact_info">
				<h4>R.J</h4>
				<p><b>Phone:</b>012-345-6789</p>
			    <strong><%= link_to 'send us email:', contact_path%></p></strong>
			</div>
		
	
				
	<strong><%= link_to "visit our facebook page", "https://www.facebook.com/rami" %></strong>
			    

       	</div>
    </div>









	

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<!DOCTYPE html>
<html lang="en">



<body>

    <div class="brand"> Real Estate Project</div>
    <div class="address-bar">3660 N. Mozart St. | Chicago, IL 66210 | 773-774-7750</div>



    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               
                <ul class="nav navbar-nav">
                    <li>
                      <%= link_to 'Home', properties_path%>
                    </li>
                    <li>
                      <%= link_to 'About Us', about_path%>
                    </li>
                     <li>
                     <%= link_to 'contact Us', contact_path%>
                     </li>
                     <li>
                     <%= link_to 'Blog', blogs_path%>
                     </li>
                      
                </div>
                    <% if user_signed_in? %>
                    Wellcome <strong><%= current_user.first_name %>&nbsp;&nbsp;</strong>
 
                   <%= link_to 'Edit profile', edit_user_registration_path %>|
                   <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
                 
                 <% else %>
                   <%= link_to "Sign up", new_user_registration_path  %> |
                   <%= link_to "Login", new_user_session_path %>
                 <% end %>

  
  
            
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    
                 
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">Real Estate Web Site</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>By
                            <strong>Rami</strong>
                        </small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    
                        
                        
                        <h1>Listing Available Properties</h1>
<table class="table table-striped">

  <thead>
      <div class="container">
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Beds</th>
      <th>Baths</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip code</th>
     
      <th>Posted Time</th>
      <th>Posted by</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.title %></td>
        <td><%= number_to_currency (property.price) %></td>
        <td><%= property.beds %></td>
        <td><%= property.baths %></td>
        <td><%= property.address %></td>
        <td><%= property.city %></td>
        <td><%= property.zip_code %></td>
       
        <td><%= time_ago_in_words (property.created_at) %></td>
        <td><%= property.user.first_name %></td>
       
        
        <!--User.find_by(id: (cureent_user.id) ).first_name-->
        
        
        
           <% if user_signed_in?%>
        <td><%= link_to 'visit', property %></td>
        <% if current_user.email == 'rami_a872000@yahoo.com' %>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
         
       <% end %>
       <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>



<%= link_to 'Publish New Property', new_property_path,class:"btn btn-success" %>
    <br>
    <br>
    <br>
    </div>                
             
                        
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Blogs You Should Read
                        <strong>Real Estate News Roundup</strong>
                    </h2>
                    <hr>
                    <p>Welcome to the first installment of the Rainier Title news roundup. Twice a month, we'll bring you the best in real estate news, information and other helpful bits of information that will help you build your business and stay ahead of the curve. This week I thought it would be good to kick things off  </p>
                    <p>with the top 10 real estate blogs from around the web. We aren't affiliated with any of these blogs, but they sure do provide some really good content that every real estate professional should know about. If I missed any, let me know in the comments!</p>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/origindex.html.erb
            
               <!-------------------------------------start my work-------------------------------------------     -->
                    
                <p id="notice"><%= notice %></p>
 
<h1>Listing Available Properties</h1>
<table class="table table-striped">

  <thead>
      <div class="container">
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Beds</th>
      <th>Baths</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip code</th>
      <th>Type</th>
      <th>Posted Time</th>
      <th>Posted by</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.title %></td>
        <td><%= number_to_currency (property.price) %></td>
        <td><%= property.beds %></td>
        <td><%= property.baths %></td>
        <td><%= property.address %></td>
        <td><%= property.city %></td>
        <td><%= property.zip_code %></td>
        <td><%= property.type.property_type %></td>
        <td><%= time_ago_in_words (property.created_at) %></td>
        <td><%= property.user.first_name %></td>
       
        
        <!--User.find_by(id: (cureent_user.id) ).first_name-->
        
        
        
        
       
       
        
           <% if user_signed_in?%>
        <td><%= link_to 'select', property %></td>
        <% if current_user.email == 'rami_a872000@yahoo.com' %>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
         
       <% end %>
       <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Publish New Property', new_property_path,class:"btn btn-success" %>
    <br>
    <br>
    <br>
    </div>                
      <!-------------------------------------end my work-------------------------------------------     -->  
      
      
     
      
      
         
               

app/views/properties/show.html.erb
<!DOCTYPE html>
<html lang="en">



<body>

    <div class="brand"> Real Estate Project</div>
    <div class="address-bar">3660 N. Mozart St. | Chicago, IL 66210 | 773-774-7750</div>



    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               
                <ul class="nav navbar-nav">
                    <li>
                      <%= link_to 'Home', properties_path%>
                    </li>
                    <li>
                      <%= link_to 'About Us', about_path%>
                    </li>
                     <li>
                     <%= link_to 'contact Us', contact_path%>
                     </li>
                     <li>
                     <%= link_to 'Blog', blogs_path%>
                     </li>
                      
                </div>
                    <% if user_signed_in? %>
                    Wellcome <strong><%= current_user.first_name %>&nbsp;&nbsp;</strong>
 
                   <%= link_to 'Edit profile', edit_user_registration_path %>|
                   <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
                 
                 <% else %>
                   <%= link_to "Sign up", new_user_registration_path  %> |
                   <%= link_to "Login", new_user_session_path %>
                 <% end %>

  
  
            
            <!-- /.navbar-collapse -->
  
        <!-- /.container -->
  






<p id="notice"><%= notice %></p>

<br><br>

        <p>
          <strong>property type :</strong>
          <%= @property.type.property_type %>
        </p>
        <p>
          <strong>Title:</strong>
          <%= @property.title %>
        </p>
        
        <p>
          <strong>Description:</strong>
          <%= @property.description %>
        </p>
        
        <p>
          <strong>Price:</strong>
          <%= number_to_currency (@property.price) %>
         
        </p>
        
        <p>
          <strong>Beds:</strong>
          <%= @property.beds %>
        </p>
        
        <p>
          <strong>Baths:</strong>
          <%= @property.baths %>
        </p>
        
        <p>
          <strong>Address:</strong>
          <%= @property.address %>
        </p>
        
        <p>
          <strong>City:</strong>
          <%= @property.city %>
        </p>
        
        <p>
          <strong>Zip code:</strong>
          <%= @property.zip_code %>
        </p>
        
        <p>
          <strong>Latitude:</strong>
          <%= @property.latitude %>
        </p>
        
        <p>
          <strong>Longitude:</strong>
          <%= @property.longitude %>
        </p>
        <p>
          <strong>posted by :</strong>
          <%= @property.user.first_name %>
        </p>
        <p>
          <strong>phone number :</strong>
          <%= @property.user.phone_number %>
        </p>
        
        <p>
          <strong>email:</strong>
          <%= @property.user.email %>
        </p>
        
        </td>
      
        <td>
          
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@property.latitude}%2C#{@property.longitude}" %>
</td>




  
  </table>

<br>



<br>


</tr>
<% if user_signed_in?%>
<%if @property.user_id == current_user.id || current_user.email == 'rami_a872000@yahoo.com' %>

    <%= link_to 'Edit your Publish property', edit_property_path(@property),class:"btn btn-warning" %> 
<td><%= link_to 'Delete your Publish property ', @property, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>

<%else%>
<td><%= link_to 'Add review', new_review_path(property_no: params[:id]) %></td>
<%end%>
<%end%>
<br>
<br>




<p>read reviews </p>
<% @property.reviews.each do |review| %>
    <strong>post by: </strong>
    <%= review.user.first_name %><br>
    <strong>Reviews: </strong>
   <%= review.rev %><br>
  <P>--------------------------</P>
  <%if current_user.id == review.user_id || current_user.email == 'rami_a872000@yahoo.com'%>
   
    <%= link_to 'Edit Review', edit_review_path(review) %>
    <%= link_to 'Delete Review', review, method: :delete, data: { confirm: 'Are you sure?' } %>
     <P>--------------------------</P>
    <br>
  <% end %>
<% end %>

<%= link_to 'Back', properties_path %>