config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :reviews
  resources :blogs
  resources :properties do 
    resources :rmrms, only: [:create]
  end 
  resources :types
 devise_for :users, controllers: {sessions: 'users/sessions' } 
 

 
 
 get 'contact', to: 'messages#new', as: 'contact'
 post 'contact', to: 'messages#create'

 root 'properties#index'

 get 'about' => 'properties#about', as: 'about'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to  properties_path (params[:property_id]) , notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to  property_path (params[:property_id]), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to  properties_path (params[:property_id]), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rev, :user_id, :property_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<!DOCTYPE html>
<html lang="en">



<body>

    <div class="brand"> Real Estate Project</div>
    <div class="address-bar">3660 N. Mozart St. | Chicago, IL 66210 | 773-774-7750</div>



    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               
                <ul class="nav navbar-nav">
                    <li>
                      <%= link_to 'Home', properties_path%>
                    </li>
                    <li>
                      <%= link_to 'About Us', about_path%>
                    </li>
                     <li>
                     <%= link_to 'contact Us', contact_path%>
                     </li>
                     <li>
                     <%= link_to 'Blog', blogs_path%>
                     </li>
                      
                </div>
                    <% if user_signed_in? %>
                    Wellcome <strong><%= current_user.first_name %>&nbsp;&nbsp;</strong>
 
                   <%= link_to 'Edit profile', edit_user_registration_path %>|
                   <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
                 
                 <% else %>
                   <%= link_to "Sign up", new_user_registration_path  %> |
                   <%= link_to "Login", new_user_session_path %>
                 <% end %>

  
  
            
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
  








<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rev %><br>
    <%= f.text_area :rev,class: "form-control" %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  
  
  
   <%= f.hidden_field :property_id, :value => params[:property_no]  %>
  
  
  
   
 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rev</th>
      <th>User</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rev %></td>
        <td><%= review.user_id %></td>
        <td><%= review.property_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rev:</strong>
  <%= @review.rev %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Property:</strong>
  <%= @review.property_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>